---@class PlayerStatus
---@field value number @0-100

---@class ServerCache
---@field statuses table<PlayerId, table<StatusName, PlayerStatus>>
---@field existingStatuses table<StatusName, true>

---@alias PlayerId integer
---@alias Character table
---@alias CharacterIdentifier string
---@alias Vector3Table {x: number, y: number, z: number}
---@alias Vehicle integer
---@alias Prop integer
---@alias Ped integer
---@alias Blip integer
---@alias Distance number
---@alias ScaleformHandle integer
---@alias NetId integer
---@alias Plate string
---@alias FailReason string
---@alias Success boolean
---@alias StatusName string